version: '2.1'

services:
  python_starter:
    image: python
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/app
    environment:
      - ENV=production
      - PORT=5000
