version: '2.1'

services:
  python-starter:
    image: python
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/app
    environment:
      - ENV=development
      - PORT=5000
  mongodb:
    image: mongo:latest
    container_name: python-starter-mongo
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27019:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
  default:
    name: python-starter